[package]
name = "ensure-update"
version = "0.1.1"
edition = "2024"

[dependencies]
abseil = { version = "0.4.0", git = "https://github.com/archer884/abseil" }
clap = { version = "4.5.53", features = ["derive", "wrap_help"] }
jiff = { version = "0.2.16", features = ["serde"] }
