[package]
name = "ensure-update"
version = "0.1.0"
edition = "2024"

[dependencies]
abseil = "0.3.0"
clap = { version = "4.5.53", features = ["derive", "wrap_help"] }
jiff = { version = "0.2.16", features = ["serde"] }
